/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.cdp.service;
import cn.zhuatech.cdp.common.BusinessException; import cn.zhuatech.cdp.dto.CdpDto.*; import cn.zhuatech.cdp.model.*; import cn.zhuatech.cdp.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class CdpService {
    private final AudienceTaskRepository orders; private final ActivationRecordRepository reports; private final DataSourceRepository dataSource; private final IdentityIssueRepository identityIssues; private final CurrentUserService current;
    public CdpService(AudienceTaskRepository orders,ActivationRecordRepository reports,DataSourceRepository dataSource,IdentityIssueRepository identityIssues,CurrentUserService current){this.orders=orders;this.reports=reports;this.dataSource=dataSource;this.identityIssues=identityIssues;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getSegmentCode();List<AudienceTask> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findBySegmentCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<AudienceTaskView> audienceTasks(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){AudienceTask order=orders.findById(id).orElseThrow(()->new BusinessException("激活任务不存在"));if(order.getStatus()==AudienceTask.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new ActivationRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<AudienceTask> list){int planned=list.stream().mapToInt(AudienceTask::getPlannedQty).sum(),done=list.stream().mapToInt(AudienceTask::getCompletedQty).sum(),defects=list.stream().mapToInt(AudienceTask::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日激活",String.format("%,d",planned),list.size()+" 张激活任务","blue"),new Metric("激活完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合规率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("数据源异常",dataSource.countByStatus(DataSource.Status.ALARM)+"",identityIssues.countByResult(IdentityIssue.Result.PENDING)+" 项待身份合并","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),dataSource.findAllByOrderByCodeAsc().stream().map(e->new DataSourceView(e.getCode(),e.getName(),e.getSegment().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),identityIssues.findTop10ByOrderByIdDesc().stream().map(i->new IdentityIssueView(i.getIdentityIssueNo(),i.getAudienceTask().getOrderNo(),i.getAudienceTask().getProductName(),i.getIdentityIssueType(),i.getIdentityIssueQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private AudienceTaskView view(AudienceTask o){return new AudienceTaskView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getSegment().getName(),o.getSegment().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(AudienceTask o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
